name: pyautolab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
      - streamlit-embedcode
      - streamlit-drawable-canvas
